excerpt_separator: ""
pygments: true
markdown: kramdown
title: 
tagline: site
description: My awesome new site via <a href="https://tinypress.co/&quot; target=&quot;_blank">Tinypress</a>
paginate: 5